export const products =  [
    {
        name: 'Delineador Liquido Punta Plumon Eye PRO',
        description: 'This is product 1',
        price: '27.000',
        inStock: true,
        imageUrl: 'https://i.imgur.com/SThEp4z.jpg',
        category: 'maquillaje',
        id: '01',

    },
    {
        name: 'Labial COLORFIX 24H',
        description: 'This is product 1',
        price: '22.500',
        inStock: true,
        imageUrl: 'https://i.imgur.com/1BGMB5l.jpg',
        category: 'maquillaje',
        id: '02',
    },
    {
        name: 'Natural Matte Base de Maquillaje',
        description: 'This is product 1',
        price: '58.125',
        inStock: true,
        imageUrl: 'https://i.imgur.com/igrd5Hs.jpg',
        category: 'maquillaje',
        id: '03',
    },
    {
        name: 'Rubor en Barra Color Stick PRO',
        description: 'This is product 1',
        price: '49.500',
        inStock: true,
        imageUrl: 'https://i.imgur.com/mJ7UDvw.jpg',
        category: 'maquillaje',
        id: '04',
    },
    {
        name: 'Natural Fresh Base de Maquillaje',
        description: 'This is product 1',
        price: '58.125',
        inStock: true,
        imageUrl: 'https://i.imgur.com/kXM6Y3t.jpg',
        category: 'maquillaje',
        id: '05',
    },
    {
        name: 'Labial COLORFIX liquid Tatto',
        description: 'This is product 1',
        price: '22.500',
        inStock: true,
        imageUrl: 'https://i.imgur.com/UF4gJ8Y.jpg',
        category: 'maquillaje',
        id: '06',
    },
    {
        name: 'Máscara de Pestañas Mega Multi Benefit',
        description: 'This is product 1',
        price: '37.400',
        inStock: true,
        imageUrl: 'https://i.imgur.com/XBiPBLr.jpg',
        category: 'maquillaje',
        id: '07',
    },
    {
        name: 'Máscara de Pestañas Mega Full Curve',
        description: 'This is product 1',
        price: '33.000',
        inStock: true,
        imageUrl: 'https://i.imgur.com/6HYPlck.jpg',
        category: 'maquillaje',
        id: '08',
    },
    {
        name: 'Máscara de Pestañas Ultra Black Extend',
        description: 'This is product 1',
        price: '35.275',
        inStock: true,
        imageUrl: 'https://i.imgur.com/zx06RsP.jpg',
        category: 'maquillaje',
        id: '09',
    },
    {
        name: 'Máscara de Pestañas Ultra Black Shock',
        description: 'This is product 1',
        price: '35.275',
        inStock: true,
        imageUrl: 'https://i.imgur.com/xrolePX.jpg',
        category: 'maquillaje',
        id: '10',
    },
    {
        name: 'Set COLORFIX Duo Tattoo x3 Edición Especial',
        description: 'This is product 1',
        price: '99.000',
        inStock: true,
        imageUrl: 'https://i.imgur.com/tZJNQjc.jpg',
        category: 'maquillaje',
        id: '11',
    },
    {
        name: 'Set Collar + Aretes Red Lover + Labial COLORFIX Duo Tattoo',
        description: 'This is product 1',
        price: '153.000',
        inStock: true,
        imageUrl: 'https://i.imgur.com/ZZkdZ2T.jpg',
        category: 'maquillaje',
        id: '12',
    },
    {
        name: 'Set Edición Especial Labiales COLORFIX Duo Tattoo',
        description: 'This is product 1',
        price: '74.250',
        inStock: true,
        imageUrl: 'https://i.imgur.com/FaRE4rM.jpg',
        category: 'maquillaje',
        id: '13',
    },
    {
        name: 'Labial Mate COLORFIX Liquid Tattoo',
        description: 'This is product 1',
        price: '37,400',
        inStock: true,
        imageUrl: 'https://i.imgur.com/mW0gDDV.jpg',
        category: 'maquillaje',
        id: '',
    },
    {
        name: '',
        description: 'This is product 1',
        price: '',
        inStock: true,
        imageUrl: '',
        category: 'maquillaje',
        id: '',
    },
    {
        name: '',
        description: 'This is product 1',
        price: '',
        inStock: true,
        imageUrl: '',
        category: 'maquillaje',
        id: '',
    },
    {
        name: '',
        description: 'This is product 1',
        price: '',
        inStock: true,
        imageUrl: '',
        category: 'maquillaje',
        id: '',
    },
    {
        name: '',
        description: 'This is product 1',
        price: '',
        inStock: true,
        imageUrl: '',
        category: 'maquillaje',
        id: '',
    },
    {
        name: '',
        description: 'This is product 1',
        price: '',
        inStock: true,
        imageUrl: '',
        category: 'maquillaje',
        id: '',
    },
    {
        name: '',
        description: 'This is product 1',
        price: '',
        inStock: true,
        imageUrl: '',
        category: 'maquillaje',
        id: '',
    },
]